apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sm-flexews

resources:
  - ../../base

commonLabels:
  datacenter: dc2
  environment: production

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
