apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sm-flexews

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

commonLabels:
  app: sm-flexews
  version: v1.0.0
