apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sm-flexews

resources:
  - namespace.yaml
  - ews-web-fe.yaml
  - ews-web-be-warning.yaml
  - ews-web-be-auth.yaml
  - ews-web-be-admin.yaml
  - ews-web-be-calc.yaml
  - ews-web-be-public.yaml
  - ews-bg-etl.yaml
  - ews-bg-auto.yaml
  - ews-bg-other.yaml
  - resource-quota.yaml
  - network-policies.yaml
  - configmaps.yaml
  - ingress.yaml

commonLabels:
  app: sm-flexews
  version: v1.0.0
