apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sm-flexews

resources:
  - namespace.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - redis.yaml
  - network-policies.yaml
  - ingress.yaml

commonLabels:
  app: sm-flexews
  version: v1.0.0
