apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DC1 overlay

namespace: sm-flexews

resources:
  - ../../base

commonLabels:
  datacenter: dc1
  environment: production

# DC1-specific patches
patches:
  - path: replica-patch.yaml
